/** @type {import('@/portfolio/core/types.js').PortfolioProjectConfig} */
const projectConfig = {
	id: "03",
	slug: "mmk1",
	route: "/portfolio/03",
	title: "MMK-1",
	summary: "Аренда башенных кранов",
	hubLogo: "/images/portfolio/case3.webp",
	models: {
		primary: "/models/case3/crane1.glb",
	},
	scene: {
		defaultCamera: { position: [0, 1.1, 10.5], lookAt: [1.15, -0.35, 0], fov: 43 },
		rootOffsetDesktop: [2.25, -2.45, 0],
		rootOffsetMobile: [0, -2.15, 0],
		scale: 1,
	},
	meta: {
		year: 2023,
		type: "ММК-1 / АРЕНДА КРАНОВ",
		skills: ["Blender", "Figma", "PS", "HTML", "CSS", "React", "Three.js"],
		accentColor: "#00bfff",
	},
	caseStudy: {
		chapterBase: 1,
		useSectionBadge: true,
		hideCategoryLabel: true,
		hideTags: true,
		statsValueFirst: true,
		metricsLayout: "verticalList",
		anchorFooterBlock: false,
		footerLabel: "ММК-1 / АРЕНДА КРАНОВ",
		footerLabelCopy: {
			en: "MMK-1 / CRANE RENTAL",
			zh: "MMK-1 / 起重机租赁",
		},
		mobileHorizontalSwipe: true,
		panelWidth: { min: 460, max: 560, ratio: 0.27 },
		contentTopPx: 100,
		contentBottomInsetPx: 48,
		leftPanel: {
			gapAfterBadge: 20,
			gapAfterTitle: 15,
			gapAfterDescription: 12,
			gapBeforeStatsRail: 0,
			categoryFontSize: 13,
			categoryLetterSpacing: 0.14,
			categoryFontWeight: 400,
			sectionBadgeShowDot: false,
			titleFontSize: 34,
			titleFontWeight: 300,
			titleLineHeightMul: 1.05,
			titleLetterSpacing: 0.055,
			descriptionFontSize: 16,
			descriptionLineHeight: 22,
			descriptionFontWeight: 300,
			descriptionUseThemeMuted: true,
			traitListGlyphSize: 32,
			traitListTopSize: 12,
			traitListBottomSize: 13,
			traitListRowPadY: 7,
			traitListGlyphColW: 64,
			traitListTextGap: 2,
			traitListNumberAlignX: 22,
			traitListIconAlignX: 22,
			traitListIconScale: 0.85,
			badgeFontSize: 13,
			badgeLetterSpacing: 0.16,
			footerAllCyan: true,
			mosaicColumns: 20,
			mosaicRows: 15,
			mosaicLiftStrength: 0.005,
			mosaicRandomLift: 150,
			mosaicScatterX: 0,
			mosaicDelay: 0.75,
		},
	},
	mediaPolicy: {
		maxVideos: 0,
		defaultLoad: "onDemand",
	},
};

export default projectConfig;
